[package]
name = "list_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "list_test"                      # The name of the target.
path = "src/listC.rs"
